### ISSUE TITLE
Liquid profiling does not work with {% liquid ... %} in theme.liquid and template liquid files

### ISSUE THREAD

**Issue by robinfritze** [Shopify/shopify-theme-inspector#62] opened 2020-07-20 14:08 UTC
### Problem

I try to profile https://de.afew-store.com/ and the Inspector is saying: "This page cannot be profiled"

### More Information

When inpecting the plugin I can see the following wrrors:
* devtools.js:16 Error: Liquid profile not found for this page
* Failed to load resource: the server responded with a status of 500 (https://afew-store.myshopify.com/?profile_liquid=true)

I can load the resource in a new browser tab without the http error.

**Comment by isAdrisal** [comment] 2020-07-27 15:37
This issue has been my experience for at least a month now. Screenshot below.

<img width="362" alt="Screen Shot 2020-07-28 at 1 36 13 am" src="https://user-images.githubusercontent.com/29012873/88561448-c64cea00-d072-11ea-9b6a-212d198d712c.png">

**Comment by wizardlyhel** [comment] 2020-07-28 22:25
@robinfritze I also can reproduce the issue on this shop. Let me investigate it a bit more and I'll get back to you on this.

**Comment by wizardlyhel** [comment] 2020-07-28 22:34
@robinfritze There is a liquid syntax error that I am seeing from your `theme.liquid`

It's the first liquid capture
```
{% liquid
  capture locale 
...
```

Maybe due to the fact that it's outside of the html tag, you don't actually see the error being rendered out

**Comment by robinfritze** [comment] 2020-08-04 14:34
> @robinfritze There is a liquid syntax error that I am seeing from your `theme.liquid`
> 
> It's the first liquid capture
> 
> ```
> {% liquid
>   capture locale 
> ...
> ```
> 
> Maybe due to the fact that it's outside of the html tag, you don't actually see the error being rendered out

@wizardlyhel 
Thank you for looking into this. Unfortunately I cannot reproduce any liquid errors and the capture statement is working as intended. Is the problem that we override the global locale variable, or do you see any other errors?

Kind regards,
Robin

**Comment by wizardlyhel** [comment] 2020-08-11 18:27
@robinfritze I tested around this and it is actually the liquid block code that the liquid profiling is failing on.
```
{% liquid
...
%}
```
and it is specific to liquid block code in `theme.liquid`

So, if we can break that liquid block code a bit, for example
```
{% capture locale %}
    {% render 'snippet-name' %}
{% endcapture %}
```
(It's fine if the snippet contains liquid block code)

This should work just fine.

We'll need to fix this on Shopify end on why liquid block code fails on profiling requests. No ETA on this.

**Comment by robinfritze** [comment] 2020-08-12 10:55
@wizardlyhel 
I am able to profile the index page after removing the {% liquid %} blocks from the theme.liquid. Unfortunately I also have to remove the {%liquid %} blocks from the template.liquid files in order to profile the corresponding pages.

**Comment by wizardlyhel** [comment] 2020-08-12 16:17
Thanks for the additional information

**Comment by ginagregory** [comment] 2020-10-19 21:11
Any update here? I use the liquid tag extensively and can't use this tool.

**Comment by cshold** [comment] 2020-10-25 14:00
Same here - we have 3 theme-store themes with the new liquid syntax and aren't able to use this anymore. Needs to stay on par with what liquid offers or it'll be another great developer tool that falls silently away like Slate

**Comment by wizardlyhel** [comment] 2020-10-26 18:16
@ginagregory @cshold 

It's a bit tight on resource at this time of year. I still don't have ETA on when I will have time to look into this.

Would you both be able to give me some code examples where you cannot push the `{% liquid ... %}` into a snippet?

**Comment by cshold** [comment] 2020-10-26 19:00
It's not about being able to use it in a snippet, it's that the compiler stops looking at files that have that syntax.

For example, on a collection page that outputs 24 products, the `for products in collection` loop doesn't show up:

![image](https://user-images.githubusercontent.com/1730309/97216215-e0928300-179b-11eb-82b3-7187553d67e4.png)

That's because right before the loop we have this:
```
{%- liquid
      assign grid_item_width = 'small--one-half medium-up--one-third'

      case per_row
        when 2
          assign grid_item_width = 'medium-up--one-half'
        when 3
          assign grid_item_width = 'small--one-half medium-up--one-third'
        when 4
          assign grid_item_width = 'small--one-half medium-up--one-quarter'
        when 5
          assign grid_item_width = 'small--one-half medium-up--one-fifth'
      endcase
    -%}

    {%- for product in collection.products -%}
      {%- render 'product-grid-item', product: product, grid_item_width: grid_item_width -%}
    {%- endfor -%}
```

**Comment by ginagregory** [comment] 2020-10-26 19:09
I can't get anywhere with the tool, I just get the "Page cannot be profiled" error. The site I'm trying on is not a development store. I've tried with both collaborator account and staff account.

**Comment by wizardlyhel** [comment] 2020-11-05 23:32
We have a fix for this - Not sure when this will be rollout (depending on code freeze situation)

**Comment by wizardlyhel** [comment] 2020-12-07 16:36
I think this fix is out - could anyone one this thread confirm this fix?

**Comment by ginagregory** [comment] 2020-12-11 20:13
Hm, I still can't get this thing to work.

**Comment by cshold** [comment] 2020-12-14 19:21
Looks like it's working for me:
![image](https://user-images.githubusercontent.com/1730309/102125328-8450f480-3e17-11eb-8c3b-ce1a45f519df.png)

Anything nested under `collection-template` is named `collection-template`, so hard to narrow down where each level of this is coming from. Good news is, once you click on one you do get the proper information from the code snippet that renders it:
![image](https://user-images.githubusercontent.com/1730309/102125426-b06c7580-3e17-11eb-8ee6-9b9315701bcc.png)

**Comment by wizardlyhel** [comment] 2021-01-04 19:17
@cshold Yea, it is on purpose that it's labelled with `section:<filename>` so that we know which file the code snippet is from.

**Comment by wizardlyhel** [comment] 2021-02-01 17:39
This should be fixed - If not feel free to reopen with more detail

**Closed** 2021-02-01 17:39 UTC
